# -*- coding: utf-8 -*-
"""Copy of Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1B-81e8iMaOiflphoxfk28WQMpgTPYPEC

import packages

---
"""

import matplotlib.pyplot as plt
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix
from google.colab import files
import seaborn as sns

from google.colab import drive 
drive.mount('/content/gdrive')

drug_df=pd.read_csv('gdrive/My Drive/drug200.csv')
drug_df.head()

drug_df['Drug'].unique()

drug_df.describe()

drug_df['Drug'].value_counts()

drug_df['Sex'] = drug_df['Sex'].map({'M': 1, 'F': 2})
drug_df['BP'] = drug_df['BP'].map({'HIGH': 1, "NORMAL" : 2, "LOW" : 3})
drug_df['Cholesterol'] = drug_df['Cholesterol'].map({'HIGH': 1, "NORMAL" : 2})
drug_df["Drug"] = drug_df["Drug"].map({"DrugY":1, "drugC":2, "drugX":3, "drugA":4, "drugB":5})

X = drug_df.drop('Drug',axis=1)
y = drug_df['Drug']

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.30, random_state = 2)

len(X_train),len(X_test)

###
import numpy as np
print(np.shape(X_train))
print(np.shape(X_test))

model = LogisticRegression(penalty='l2',solver='newton-cg')
model.fit(X_train,y_train)

print(f"Accuracy score for logistic regression model is {model.score(X_test,y_test)*100}")

predict = model.predict(X_test)
cf = confusion_matrix(y_test,predict)
x=['Y','X','A','B','C']
y=['Y','X','A','B','C']
sns.heatmap(cf, yticklabels=y,xticklabels=x, cmap='Reds',annot=True)

# Classification report for Logistic Regression
from sklearn import metrics
print(metrics.classification_report(y_test,predict))

